### ISSUE TITLE
[FATAL]  Initializer: System.ArgumentException: Max message length is 2000

### ISSUE THREAD

**Issue by fank** [Fankserver/torchapi-discord-bridge#1]
```
23:59:38.7695 [FATAL]  Initializer: System.ArgumentException: Max message length is 2000
   at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d__39.MoveNext()
System.ArgumentException: Max message length is 2000
   at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d__39.MoveNext()
23:59:38.7695 [FATAL]  Initializer: System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Max message length is 2000
   at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d__39.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SEDiscordBridge.DiscordBridge.SendCmdResponse(String response, DiscordChannel chann) in C:\Users\Fank\Documents\GitHub\SEDiscordBridge\SEDiscordBridge\DiscordBridge.cs:line 0
   at SEDiscordBridge.DiscordBridge.<>c__DisplayClass15_0.<Discord_MessageCreated>b__0() in C:\Users\Fank\Documents\GitHub\SEDiscordBridge\SEDiscordBridge\DiscordBridge.cs:line 171
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at RunSingleFrame_0(Object )
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\VRageGame.cs:line 241
   at Torch.VRageGame.Run() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\VRageGame.cs:line 118
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
---> (Inner Exception #0) System.ArgumentException: Max message length is 2000
   at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d__39.MoveNext()<---

System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Max message length is 2000
   at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d__39.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SEDiscordBridge.DiscordBridge.SendCmdResponse(String response, DiscordChannel chann) in C:\Users\Fank\Documents\GitHub\SEDiscordBridge\SEDiscordBridge\DiscordBridge.cs:line 0
   at SEDiscordBridge.DiscordBridge.<>c__DisplayClass15_0.<Discord_MessageCreated>b__0() in C:\Users\Fank\Documents\GitHub\SEDiscordBridge\SEDiscordBridge\DiscordBridge.cs:line 171
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at RunSingleFrame_0(Object )
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\VRageGame.cs:line 241
   at Torch.VRageGame.Run() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\VRageGame.cs:line 118
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
---> (Inner Exception #0) System.ArgumentException: Max message length is 2000
   at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d__39.MoveNext()<---

23:59:38.7695 [FATAL]  Initializer: System.ArgumentException: Max message length is 2000
   at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d__39.MoveNext()
System.ArgumentException: Max message length is 2000
   at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d__39.MoveNext()
```

**Comment by FabioZumbi12** [comment]
This error not happens on latest versions. What version of SEDB you is using?
See the filter: https://github.com/Fankserver/SEDiscordBridge/blob/master/SEDiscordBridge/DiscordBridge.cs#L171

**Comment by fank** [comment]
Yea but my messages are greater than 4000 chars
